import 'package:arcane_jaspr/arcane_jaspr.dart';
import 'package:jaspr/dom.dart' as dom;
import 'package:jaspr_lucide/jaspr_lucide.dart' as lucide;

class KBIcon {
  const KBIcon._();

  static Widget build(
    String iconName, {
    IconSize size = IconSize.sm,
    String? classes,
  }) {
    String value = iconName.trim().toLowerCase();
    dom.Unit dimension = dom.Unit.pixels(size.pixels);
    String? className = classes;
    Map<String, String> attributes = const <String, String>{
      'aria-hidden': 'true',
      'focusable': 'false',
    };

    return switch (value) {
      'file-text' => lucide.FileText(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'file' => lucide.File(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'book' => lucide.Book(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'book-open' => lucide.BookOpen(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'notebook' => lucide.Notebook(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'scroll' => lucide.Scroll(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'rocket' => lucide.Rocket(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'zap' => lucide.Zap(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'home' => lucide.House(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'play' => lucide.Play(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'compass' => lucide.Compass(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'map' => lucide.Map(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'navigation' => lucide.Navigation(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'server' => lucide.Server(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'database' => lucide.Database(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'hard-drive' => lucide.HardDrive(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'cpu' => lucide.Cpu(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'cloud' => lucide.Cloud(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'globe' => lucide.Globe(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'network' => lucide.Network(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'wifi' => lucide.Wifi(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'monitor' => lucide.Monitor(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'laptop' => lucide.Laptop(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'container' => lucide.Container(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'shield' => lucide.Shield(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'shield-check' => lucide.ShieldCheck(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'shield-alert' => lucide.ShieldAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'lock' => lucide.Lock(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'unlock' => lucide.LockOpen(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'key' => lucide.Key(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'key-round' => lucide.KeyRound(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'scan' => lucide.Scan(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'settings' => lucide.Settings(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'settings-2' => lucide.Settings2(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'sliders' => lucide.SlidersHorizontal(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'sliders-horizontal' => lucide.SlidersHorizontal(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'wrench' => lucide.Wrench(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'hammer' => lucide.Hammer(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'terminal' => lucide.Terminal(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'code' => lucide.Code(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'braces' => lucide.Braces(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'brackets' => lucide.Brackets(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'folder' => lucide.Folder(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'folder-open' => lucide.FolderOpen(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'folder-closed' => lucide.FolderClosed(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'archive' => lucide.Archive(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'package' => lucide.Package(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'box' => lucide.Box(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'mail' => lucide.Mail(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'message-circle' => lucide.MessageCircle(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'message-square' => lucide.MessageSquare(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'headphones' => lucide.Headphones(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'phone' => lucide.Phone(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'bell' => lucide.Bell(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'activity' => lucide.Activity(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'bar-chart' => lucide.ChartBar(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'line-chart' => lucide.ChartLine(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'pie-chart' => lucide.ChartPie(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'gauge' => lucide.Gauge(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'clock' => lucide.Clock(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'timer' => lucide.Timer(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'refresh-cw' => lucide.RefreshCw(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'rotate-cw' => lucide.RotateCw(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'loader' => lucide.Loader(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'credit-card' => lucide.CreditCard(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'dollar-sign' => lucide.DollarSign(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'receipt' => lucide.Receipt(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'wallet' => lucide.Wallet(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'coins' => lucide.Coins(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'banknote' => lucide.Banknote(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'user' => lucide.User(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'users' => lucide.Users(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'user-plus' => lucide.UserPlus(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'user-check' => lucide.UserCheck(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'user-cog' => lucide.UserCog(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'layers' => lucide.Layers(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'layout' => lucide.LayoutGrid(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'grid' => lucide.Grid3x3(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'sparkles' => lucide.Sparkles(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'sun' => lucide.Sun(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'moon' => lucide.Moon(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'palette' => lucide.Palette(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'star' => lucide.Star(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'heart' => lucide.Heart(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'flag' => lucide.Flag(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'bookmark' => lucide.Bookmark(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'tag' => lucide.Tag(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'tags' => lucide.Tags(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'info' => lucide.Info(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'alert-triangle' => lucide.TriangleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'alert-circle' => lucide.CircleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'help-circle' => lucide.CircleQuestionMark(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'check' => lucide.Check(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'check-circle' => lucide.CircleCheck(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'x' => lucide.X(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'x-circle' => lucide.CircleX(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'arrow-right' => lucide.ArrowRight(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'arrow-left' => lucide.ArrowLeft(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'arrow-up' => lucide.ArrowUp(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'arrow-down' => lucide.ArrowDown(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'chevron-right' => lucide.ChevronRight(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'chevron-left' => lucide.ChevronLeft(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'chevron-up' => lucide.ChevronUp(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'chevron-down' => lucide.ChevronDown(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'external-link' => lucide.ExternalLink(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'link' => lucide.Link(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'github' => lucide.GitFork(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'discord' => lucide.MessageCircle(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'download' => lucide.Download(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'upload' => lucide.Upload(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'copy' => lucide.Copy(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'clipboard' => lucide.Clipboard(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'trash' => lucide.Trash(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'trash-2' => lucide.Trash2(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'edit' => lucide.SquarePen(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'pencil' => lucide.Pencil(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'save' => lucide.Save(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'plus' => lucide.Plus(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'minus' => lucide.Minus(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'search' => lucide.Search(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'filter' => lucide.Funnel(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'eye' => lucide.Eye(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'eye-off' => lucide.EyeOff(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'life-buoy' => lucide.LifeBuoy(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'help' => lucide.CircleQuestionMark(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'power' => lucide.Power(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'plug' => lucide.Plug(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'plug-zap' => lucide.PlugZap(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'battery' => lucide.Battery(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'map-pin' => lucide.MapPin(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'building' => lucide.Building(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'building-2' => lucide.Building2(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'calendar' => lucide.Calendar(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'panel' => lucide.PanelRight(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'frame' => lucide.Square(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'columns' => lucide.Columns2(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'component' => lucide.Blocks(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'table' => lucide.Table(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'type' => lucide.Type(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'film' => lucide.Film(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'lightbulb' => lucide.Lightbulb(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'important' => lucide.CircleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'warning' => lucide.TriangleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'caution' => lucide.OctagonAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'tip' => lucide.Lightbulb(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'note' => lucide.Info(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'octagon-alert' => lucide.OctagonAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'triangle-alert' => lucide.TriangleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      'circle-alert' => lucide.CircleAlert(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
      _ => lucide.FileText(
        width: dimension,
        height: dimension,
        classes: className,
        attributes: attributes,
      ),
    };
  }
}
